{"name": "Принятие заказа без id заказа", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test_take_order.TestTakeOrder object at 0x106667c10>, create_courier = 281689\n\n    @allure.title('Принятие заказа без id заказа')\n    def test_take_order_without_id_order(self, create_courier):\n        id_courier = create_courier\n        response_take_order = requests.put(f'{Const.TAKE_ORDER}?courierId={id_courier}')\n        print(response_take_order.text)\n        # Баг на бэке. Присылается 'code:404,message:Not Found'\n>       assert response_take_order.status_code == 400\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntest/test_take_order.py:22: AssertionError"}, "attachments": [{"name": "stdout", "source": "eaeeb7b2-c798-4887-bd27-10798902058f-attachment.txt", "type": "text/plain"}], "start": 1711789207121, "stop": 1711789207187, "uuid": "dd9274ea-bc1c-48ab-9e3b-fba768a6c91f", "historyId": "0463a2bcc10c170e302ead7a61ace750", "testCaseId": "0463a2bcc10c170e302ead7a61ace750", "fullName": "test.test_take_order.TestTakeOrder#test_take_order_without_id_order", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_take_order"}, {"name": "subSuite", "value": "TestTakeOrder"}, {"name": "host", "value": "MacBook-Air-Antonina.local"}, {"name": "thread", "value": "88417-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_take_order"}]}